var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/scan/route.js")
R.c("server/chunks/node_modules_next_0b_ftxu._.js")
R.c("server/chunks/node_modules_zod_v4_classic_1puff4q._.js")
R.c("server/chunks/node_modules_zod_v4_core_03961oy._.js")
R.c("server/chunks/node_modules_zod_v4_locales_0on3-qh._.js")
R.c("server/chunks/node_modules_undici_lib_dispatcher_0wsv20j._.js")
R.c("server/chunks/node_modules_undici_lib_llhttp_0za4hxz._.js")
R.c("server/chunks/node_modules_undici_lib_web_0aaxqvf._.js")
R.c("server/chunks/node_modules_undici_lib_1bi8efe._.js")
R.c("server/chunks/node_modules_undici_index_00yosc1.js")
R.c("server/chunks/[root-of-the-server]__0y4mxk_._.js")
R.c("server/chunks/_next-internal_server_app_api_scan_route_actions_0_k8ox1.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/scan/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/scan/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
