var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0_jtnl8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06w5evc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00l4bm5._.js")
R.c("server/chunks/ssr/[externals]_next_dist_compiled_@vercel_og_index_node_088pigq.js")
R.c("server/chunks/ssr/_1yngdjl._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nw7kvr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_0hhsz1j.js")
R.m(72087)
module.exports=R.m(72087).exports
