var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__19wp5_c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06w5evc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__00l4bm5._.js")
R.c("server/chunks/ssr/[externals]_next_dist_compiled_@vercel_og_index_node_088pigq.js")
R.c("server/chunks/ssr/_1yngdjl._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nw7kvr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_0pt47yr.js")
R.m(61878)
module.exports=R.m(61878).exports
